server:
  port: 8282

management:
  endpoints:
    web:
      exposure:
        include: gateway

spring:
  application:
    name: gatewayservice
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: userservice
        uri: lb://userservice
        predicates:
          - Path=/auth/**

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka/}